---
title: "Missingness analysis"
author: Amelia Tan, Arianna Dagliati, Trang Le
date: "27 October 2020"
---


```{r setup, warning=FALSE, message=FALSE}
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(forcats)

theme_set(theme_bw() + 
            theme(legend.title = element_blank(),
                  panel.grid.minor = element_blank()))
```

## Read in files 
and convert to wide format
```{R}
#4CE long format Labs Data
patient_obs <- read_csv('simulated-data/patients-observations.csv')
#IDs of severe subject and date of the first severe event
severity <- read_csv('simulated-data/severity.csv')
#Code, Descriptions and Ranges
lab_mapping <- read_csv('public-data/loinc-map.csv')
```

```{R}
patient_obs_wide <- patient_obs %>% 
  left_join(lab_mapping, by = c('concept_code' = 'LOINC')) %>% 
  select(- concept_code) %>% 
  pivot_wider(id_cols = c(patient_num, days_since_admission),
              names_from = short_name,
              values_from = value,
              values_fn = mean)

#check NAs in the Wide format
sum(is.na(patient_obs_wide))
```

## Number of observation (days) per patient
```{R}
days_count_min_max <- patient_obs_wide %>%
  group_by(patient_num) %>%
  summarise(
    n = n_distinct(days_since_admission),
    min = min(days_since_admission),
    max = max(days_since_admission),
    .groups = 'drop'
  ) %>% 
  mutate(time_obs = max - min,
         severity = patient_num %in% unique(severity$covid_id)) 

summary(days_count_min_max$n)
```

## Histogram of the number of days with at least one observation
```{R}
days_bar <- days_count_min_max %>% 
  ggplot(aes(x = n, fill = severity)) +
  geom_bar(alpha = 0.5) +
  scale_fill_brewer(palette = 'Dark2', direction = -1) +
  labs(fill = 'Severe?', 
       x = "Number of days with data", 
       y = "Count")

days_bar
```

## Histogram of length of stay
i.e. last day with observation-first day with observation

We need to check for readmission here.
```{R}
period_bar <- days_count_min_max %>% 
  ggplot(aes(x = time_obs, fill = severity)) +
  geom_bar(alpha = 0.5) +
  scale_fill_brewer(palette = 'Dark2', direction = -1) +
  labs(fill = 'Severe?', 
       x = "Length of stay (last day - first day)", 
       y = "Count")

period_bar
```

## Analyze missingness and frequency of measures for each lab

```{r}
patient_obs_long <- patient_obs_wide %>% 
  pivot_longer(-c(patient_num, days_since_admission),
               names_to = 'lab', values_to = 'value',
               values_drop_na = TRUE) %>% 
  mutate(severity = patient_num %in% 
      unique(severity$covid_id) %>% 
      as_factor() %>% 
      fct_recode('nonsevere' = 'FALSE', 'severe' = 'TRUE')) 
  
per_lab <- patient_obs_long %>% 
  group_by(lab, patient_num, severity) %>% 
  count(name = 'n_obs') %>% 
  ungroup() %>% 
  group_by(lab, severity) %>% 
  count(n_obs) %>% 
  ungroup() %>% 
  pivot_wider(names_from = severity, values_from = n, values_fill = 0) %>% 
  mutate(both_severities = nonsevere + severe) %>% 
  group_by(lab) %>% 
  # mutate(total = sum(both_severities)) %>% 
  # ungroup() %>% 
  mutate(prop_nonsevere = nonsevere/sum(nonsevere),
         prop_severe = severe/sum(severe),
         prop_both = both_severities/sum(both_severities)) %>% 
  ungroup()
  
```

```{r}
lab_medians <-
  patient_obs_long %>% 
  add_count(lab, name = 'total_obs') %>% 
  group_by(lab) %>% 
  mutate(total_patients = length(unique(patient_num))) %>% 
  add_count(patient_num, name = 'n_obs_patients') %>% 
  mutate(median_obs_per_patient = median(n_obs_patients),
         n_greater0 = n_obs_patients > median_obs_per_patient,
         n_greater1 = n_obs_patients > median_obs_per_patient + 1,
         n_greater2 = n_obs_patients > median_obs_per_patient + 2) %>% 
  group_by(severity) %>% 
  mutate(each_med_obs_per_patient = median(n_obs_patients)) %>% 
  ungroup(severity) %>% 
  select(- c(days_since_admission, value)) %>% 
  distinct() %>% 
  group_by(lab) %>% 
  mutate(across(contains('n_greater'), sum)) %>% 
  select(- c(n_obs_patients, patient_num)) %>% 
  distinct() %>% 
  pivot_wider(names_from = severity, values_from = each_med_obs_per_patient) %>% 
  rename('median_obs_per_severe_patient' = severe,
         'median_obs_per_non_severe_patient' = nonsevere)

```

```{r}
colnames(lab_medians)
lab_medians %>% 
  select(lab, total_obs, total_patients) %>%
  pivot_longer(- lab) %>% 
  ggplot(aes(x = value, y = fct_reorder(lab, value))) +
  geom_col() +
  facet_grid(cols = vars(name), scales = 'free_x', space = 'free') +
  labs(y = NULL)
```


```{r fig.width=12}
patient_obs_long %>% 
  left_join(lab_mapping, by = c('lab' = 'short_name')) %>% 
  ggplot(aes(x = severity, y = value, fill = severity)) +
  geom_violin() +
  geom_hline(aes(yintercept = `Reference Low`), linetype = 'dashed') +
  scale_fill_brewer(palette = 'Dark2') +
  geom_hline(aes(yintercept = `Reference High`)) +
  facet_wrap(~ lab, scales = 'free') +
  theme(legend.position = 'None')
```

## Missing data heatmap
```{r fig.width=12}
per_lab %>% 
  select(lab, n_obs, both_severities, severe, nonsevere) %>% 
  pivot_longer(c(both_severities, severe, nonsevere)) %>% 
  ggplot(aes(x = n_obs, fill = value, y = fct_reorder(lab, n_obs))) + 
  geom_tile(colour = "white", size = 0.2)+
  geom_text(aes(label = value), colour = "white", size = 2) +
  scale_y_discrete(expand = c(0, 0))+
  scale_x_continuous(expand = c(0, 0),
                     breaks = c(1:max(per_lab$n_obs)),
                     labels = c(1:max(per_lab$n_obs)))+
  scale_fill_gradient(low = "lightgrey", high = "darkblue",
                      limits = c(0, max(per_lab$both_severities))) +
  facet_wrap(~ name, nrow = 1) +
  labs(x = 'Number of values a patient has for each lab',
       y = NULL, fill = '# patients') +
  theme(panel.grid.major = element_blank(),
        legend.position = c(0.93, 0.2),
        axis.ticks.y = element_blank()
  )

```


```{r fig.width=12}
per_lab %>% 
  select(lab, n_obs, prop_both, prop_severe, prop_nonsevere) %>% 
  pivot_longer(c(prop_both, prop_severe, prop_nonsevere)) %>% 
  ggplot(aes(x = n_obs, fill = value, y = fct_reorder(lab, n_obs))) + 
  geom_tile(colour = "white", size = 0.2)+
  geom_text(aes(label = round(value, 2)), colour = "white", size = 2) +
  scale_y_discrete(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0),
                     breaks = c(1:max(per_lab$n_obs)),
                     labels = c(1:max(per_lab$n_obs)))+
  scale_fill_gradient(low = "lightgrey", high = "darkblue",
                      labels = scales::percent_format(accuracy = 1L)) +
  facet_wrap(~ name, nrow = 1) +
  labs(x = 'Number of values a patient has for each lab',
       y = NULL, fill = '# patients') +
  theme(panel.grid.major = element_blank(),
        legend.position = c(0.93, 0.2),
        axis.ticks.y = element_blank()
  )
```


```{r}
sessionInfo()
```